### ISSUE TITLE
HTML parsing error

### ISSUE THREAD

**Issue by ghost** [MojoFilter/Puffincast#6]
'Various' is an unexpected token. Expecting white space. Line 1501, position 57.

I searched for "Run" as a song title.

In ILibraryProvider.cs  
In Query()

**Comment by MojoFilter** [comment]
That might explain a lot of the mysteriously unmatchables

**Comment by MojoFilter** [comment]
I'm guessing this is the culprit:

`[<a class='browse' href="right.html?query=?artist LIKE "Various%%20Artists"">Various Artists</a>]`

**Comment by MojoFilter** [comment]
https://github.com/MojoFilter/Puffincast/commit/74064d27308fa3952cf0755cdaffce56d726f46e
